### ISSUE TITLE
Confusing about the definition of binary attribute

### ISSUE THREAD

**Issue by berylsheep-up** [genforce/interfacegan#47]
Hello! I am confusing about the definition of binary attribute.  For example, if I want to change the hair color attribute, whether the method can only work for dart colors vs. light colors. Can i get the centain color direction like red hair color direction through collecting red hair and no red hair images to train a  
binary classifier? Maybe can we get the red color direction through collecting red hair and yellow hair?

**Comment by ShenYujun** [comment]
Red v.s. non-red is possible. Then, you should be able to change any color to red (but I am not sure what the negative direction means). About red v.s. yellow, I don't think it will work. I mean, since hair color is diverse, we may not be able to use a linear subspace to represent all colors. In other words, "red v.s. non-red" and "yellow v.s. non-yellow" should be two directions. So I would suggest collect red hair and other-color hair.
